### ISSUE TITLE
Erreur "cannot read property map"

### ISSUE THREAD

**Issue by Freezman31** [Litarvan/pronote-api#100]
J'utilise l'api pronote pour essayer si cela marche avec mes codes.
Voici mon code : 
```
async function main()
{
    const session = await pronote.login(url, username, password, cas);
    
    console.log(session.user.name); // Affiche le nom de l'élève
    console.log(session.user.studentClass.name); // Affiche la classe de l'élève
    
    const timetable = await session.timetable(); // Récupérer l'emploi du temps d'aujourd'hui
    const marks = await session.marks(); // Récupérer les notes du trimestre
    
    console.log(`L'élève a ${timetable.length} cours aujourd'hui`); 
    console.log(`et a pour l'instant une moyenne de ${marks.averages.student} ce trimestre.`);
    
    // etc. les fonctions utilisables sont 'timetable', 'marks', 'contents', 'evaluations', 'absences',
    // 'infos', et 'menu', sans oublier les champs 'user' et 'params' qui regorgent d'informations.
}

main().catch(err => {
    if (err.code === pronote.errors.WRONG_CREDENTIALS.code) {
        console.error('Mauvais identifiants');
    } else {
        console.error(err);
    }
}); 
```
je vous mets pas mes codes ni mon cas. et j'ai ça comme erreur après qu'on me récupère mon nom et ma classe : 
```
TypeError: Cannot read property 'map' of undefined
    at getTimetable (C:\Users\jevouslditpas\node_modules\pronote-api\src\fetch\pronote\timetable.js:40:39)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timetable (C:\Users\jevouslditpas\node_modules\pronote-api\src\fetch\timetable.js:26:27)
    at async main (C:\Users\jevouslditpas\Documents\pronote.js:16:23)
```
Une idée ?

**Comment by trmaud** [comment]
Hello,

Tu a un emploit du temps sur ton pronote ?
Car la il dit qu'il trouvent rien sur pronote.

Cdt
Thibaut

**Comment by Freezman31** [comment]
Je n'ai pas d'emploi du temps un samedi... et je ne peux pas non plus avoir accès à celui de la semaine prochaine (une belle avancé technologique..).
je vais essayer avec une date précise
Merci
Freezman

**Comment by Litarvan** [comment]
Je garde ouvert parce que le crash est quand même pas normal, je vais essayer de régler ça

**Comment by Litarvan** [comment]
J'ai rajouté une vérification du coup
