### ISSUE TITLE
Ajouter le cas Aix-Marseille

### ISSUE THREAD

**Issue by Ayfri** [Litarvan/pronote-api#131]
J'ai remarqué qu'il manque le CAS Aix-Marseille, voici le lien : https://www.cas-marseille.fr/fr/

**Comment by Androz2091** [comment]
Il manque peut-être le CAS Aix-Marseille mais je suis pas sur que le lien soit correct. Le Comité d'Action Sociale n'a surement rien à voir avec la connexion à Pronote non ? D'après ce que j'ai pu voir, tous les lycées d'Aix-Marseille ont une page d'authentification comme celle-ci: http://www.lyc-monnet.ac-aix-marseille.fr/sitepublic/spip.php?page=login&url=spip.php%3Frubrique190.

**Comment by Ayfri** [comment]
Non, dans mon lycée nous utilisons une plateforme nommée Atrium qui permet ensuite de se connecter à Pronote (il n'y a pas besoin de se connecter à pronote du coup).

**Comment by Androz2091** [comment]
Ok, je pense que ça dépend des lycées, c'est pareil en occitanie, certains fonctionnent avec mon-ent-occitanie, d'autres avec e-college, etc.

**Comment by ThibautTrarbach** [comment]
Pour info, le lien du cas est pas sont lien, mais celui ci : 
atrium-sud.fr

Cdt
Thibaut

**Comment by Ayfri** [comment]
Du coup quelle est la situation actuelle ?

**Comment by ThibautTrarbach** [comment]
Une personne est en train de le rendre compatible dans le pull requests :  https://github.com/Litarvan/pronote-api/pull/141

Cdt
Thibaut

**Comment by Ayfri** [comment]
Parfait.

**Comment by ThibautTrarbach** [comment]
Disponibles dans la branche master, 

Je te laisse faire les test.

Cdt
Thibaut

**Comment by Ayfri** [comment]
Quand je me connecte j'obtiens cette erreur :
```js
Error: Request failed with status code 404
    at createError (C:\Users\Pierre\WebstormProjects\bots\pronote-bot\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Pierre\WebstormProjects\bots\pronote-bot\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Pierre\WebstormProjects\bots\pronote-bot\node_modules\axios\lib\adapters\http.js:244:11)
    at IncomingMessage.emit (node:events:339:22)
    at endReadableNT (node:internal/streams/readable:1289:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  config: {
    url: 'https://0130003h.index-education.net/?ticket=ST-282828-SqjQzv9Gc7d3dBgjgdI4-atrium-cas',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0',
      'Content-Type': '',
      Cookie: 'JSESSIONID=BED3A66FAD0E6B5CA1BB7638104E8846; CASPRIVACY=""; CASTGC=TGT-130318-7blWCRKMCH9rNbZYm9jpZBJI9kemRgF74ywZHjzbA79TMmwQLZ-atrium-cas'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    maxRedirects: 0,
    validateStatus: [Function: validateStatus],
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      error: [Function: handleRequestError],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: '0130003h.index-education.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: '0130003h.index-education.net',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 182,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /?ticket=ST-282828-SqjQzv9Gc7d3dBgjgdI4-atrium-cas HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\n' +
      'Content-Type: \r\n' +
      'Cookie: JSESSIONID=BED3A66FAD0E6B5CA1BB7638104E8846; CASPRIVACY=""; CASTGC=TGT-130318-7blWCRKMCH9rNbZYm9jpZBJI9kemRgF74ywZHjzbA79TMmwQLZ-atrium-cas\r\n' +
      'Host: 0130003h.index-education.net\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/?ticket=ST-282828-SqjQzv9Gc7d3dBgjgdI4-atrium-cas',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '0130003h.index-education.net',
    protocol: 'https:',
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      'content-type': [Array],
      cookie: [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'content-type': 'text/html; charset=us-ascii',
      server: 'Microsoft-HTTPAPI/2.0',
      date: 'Sat, 31 Oct 2020 17:10:31 GMT',
      connection: 'close',
      'content-length': '315'
    },
    config: {
      url: 'https://0130003h.index-education.net/?ticket=ST-282828-SqjQzv9Gc7d3dBgjgdI4-atrium-cas',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      maxRedirects: 0,
      validateStatus: [Function: validateStatus],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /?ticket=ST-282828-SqjQzv9Gc7d3dBgjgdI4-atrium-cas HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0\r\n' +
        'Content-Type: \r\n' +
        'Cookie: JSESSIONID=BED3A66FAD0E6B5CA1BB7638104E8846; CASPRIVACY=""; CASTGC=TGT-130318-7blWCRKMCH9rNbZYm9jpZBJI9kemRgF74ywZHjzbA79TMmwQLZ-atrium-cas\r\n' +
        'Host: 0130003h.index-education.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/?ticket=ST-282828-SqjQzv9Gc7d3dBgjgdI4-atrium-cas',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '0130003h.index-education.net',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">\r\n' +
      '<HTML><HEAD><TITLE>Not Found</TITLE>\r\n' +
      '<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>\r\n' +
      '<BODY><h2>Not Found</h2>\r\n' +
      '<hr><p>HTTP Error 404. The requested resource is not found.</p>\r\n' +
      '</BODY></HTML>\r\n'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by ThibautTrarbach** [comment]
Hello,

des nouvelle ?

cdt
Thibaut

**Comment by ThibautTrarbach** [comment]
@MeatReed Tu peux regarder l'erreur STP.

Cdt
Thibaut

**Comment by ThibautTrarbach** [comment]
Hello,

Suite a aucune  réponse de l'utilisateur et un test concluant de mon coté, je ferme l'issue.

Cdt
Thibaut
