### ISSUE TITLE
erreur server

### ISSUE THREAD

**Issue by Shaar-games** [Litarvan/pronote-api#15]
TypeError: Cannot read property 'V' of undefined
    at timetable.donnees.ListeCours.forEach.lesson (/root/nodejs/pronote/src/pro                                                                        note.js:600:38)
    at Array.forEach (<anonymous>)
    at readWeek (/root/nodejs/pronote/src/pronote.js:579:38)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Litarvan** [comment]
Salut, ce genre de problème a normalement été réglé avec la nouvelle version, n'hésite pas à nous prévenir s'il réapparaît
