### ISSUE TITLE
TypeError: Cannot read property 'L' of undefined

### ISSUE THREAD

**Issue by busybox11** [Litarvan/pronote-api#74]
I get this error with an almost-empty account.

Here is the complete trace outputed by node:
```
TypeError: Cannot read property 'L' of undefined
    at /home/busybox/dev/probote-v2/node_modules/pronote-api/src/fetch/pronote/user.js:46:51
    at fromPronote (/home/busybox/dev/probote-v2/node_modules/pronote-api/src/data/objects.js:21:18)
    at /home/busybox/dev/probote-v2/node_modules/pronote-api/src/data/types.js:73:57
    at Array.map (<anonymous>)
    at Array.value.pronoteMap (/home/busybox/dev/probote-v2/node_modules/pronote-api/src/data/types.js:73:48)
    at getUser (/home/busybox/dev/probote-v2/node_modules/pronote-api/src/fetch/pronote/user.js:42:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.login (/home/busybox/dev/probote-v2/node_modules/pronote-api/src/auth.js:37:20)
    at async Object.logIn (/home/busybox/dev/probote-v2/pronote/index.js:8:15)
```

**Comment by Litarvan** [comment]
Hey, just push a fix, can you try by replacing node_modules/pronote-api/ with the content of https://github.com/Litarvan/pronote-api/archive/master.zip ?

**Comment by busybox11** [comment]
I'll try this later. Thanks for the help.

**Comment by Litarvan** [comment]
I released a new version with the fix, when you'll try you can just use `npm i --save pronote-api` to update

**Comment by Litarvan** [comment]
Any update ?

**Comment by busybox11** [comment]
Yup, working. Thanks :)
